#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using UnityEditor;
using UnityEngine;

public static class CharacterVerificationProfileBuilder
{
    private const string RootFolder =
        "Assets/2. Data/CharacterVerification";

    private const string AutoFolder =
        RootFolder + "/AutoGenerated";

    [MenuItem(
        "Tools/Project Abyss/Character Verification/Create or Refresh Default Profiles")]
    public static void CreateOrRefreshAllProfiles()
    {
        EnsureFolders();

        CharacterVerificationProjectRepair
            .RepairAll(logResult: false);

        string[] bundleGuids =
            AssetDatabase.FindAssets(
                "t:CharacterAuthoringBundle");

        int created = 0;
        int updated = 0;

        for (int i = 0;
             i < bundleGuids.Length;
             i++)
        {
            string path =
                AssetDatabase.GUIDToAssetPath(
                    bundleGuids[i]);

            CharacterAuthoringBundle bundle =
                AssetDatabase.LoadAssetAtPath<
                    CharacterAuthoringBundle>(
                        path);

            if (bundle == null)
                continue;

            CharacterVerificationPrefabResolver.TryRepair(
                bundle,
                out _,
                out _,
                saveAssets: false);

            bool existed =
                FindProfile(bundle) != null;

            CharacterVerificationProfile profile =
                GetOrCreateProfile(bundle);

            if (profile == null)
                continue;

            if (existed)
                updated++;
            else
                created++;
        }

        AssetDatabase.SaveAssets();
        AssetDatabase.Refresh();

        Debug.Log(
            "[CharacterVerification] Default Profiles 갱신 완료 / " +
            $"Created={created}, Updated={updated}");
    }

    public static CharacterVerificationProfile
        GetOrCreateProfile(
            CharacterAuthoringBundle bundle)
    {
        if (bundle == null)
            return null;

        CharacterVerificationProjectRepair.RepairBundle(
            bundle,
            out _,
            saveAssets: false);

        EnsureFolders();

        CharacterVerificationProfile profile =
            FindProfile(bundle);

        if (profile == null)
        {
            string fileName =
                Sanitize(
                    string.IsNullOrWhiteSpace(
                        bundle.DisplayName)
                        ? bundle.name
                        : bundle.DisplayName);

            string path =
                AssetDatabase.GenerateUniqueAssetPath(
                    $"{AutoFolder}/{fileName}_Verification.asset");

            profile =
                ScriptableObject.CreateInstance<
                    CharacterVerificationProfile>();

            AssetDatabase.CreateAsset(
                profile,
                path);
        }

        Dictionary<string, CharacterVerificationCaseDefinition>
            existingById =
                profile.Cases?
                    .Where(
                        item =>
                            item != null &&
                            !string.IsNullOrWhiteSpace(
                                item.CaseId))
                    .GroupBy(
                        item => item.CaseId,
                        StringComparer.Ordinal)
                    .ToDictionary(
                        group => group.Key,
                        group => group.First(),
                        StringComparer.Ordinal) ??
                new Dictionary<string, CharacterVerificationCaseDefinition>(
                    StringComparer.Ordinal);

        List<CharacterVerificationCaseDefinition> cases =
            CharacterVerificationCaseProviderRegistry
                .BuildDefaultCases(bundle)
                .ToList();

        for (int i = 0;
             i < cases.Count;
             i++)
        {
            CharacterVerificationCaseDefinition generated =
                cases[i];

            if (generated == null ||
                !existingById.TryGetValue(
                    generated.CaseId,
                    out CharacterVerificationCaseDefinition existing))
            {
                continue;
            }

            generated.Enabled =
                existing.Enabled;

            generated.Seed =
                existing.Seed;
        }

        profile.Configure(
            BuildProfileId(bundle),
            bundle,
            cases,
            strictPresentation:
                profile.StrictPresentationValidation);

        EditorUtility.SetDirty(profile);

        return profile;
    }

    public static CharacterVerificationProfile
        FindProfile(
            CharacterAuthoringBundle bundle)
    {
        if (bundle == null)
            return null;

        string[] guids =
            AssetDatabase.FindAssets(
                "t:CharacterVerificationProfile");

        for (int i = 0;
             i < guids.Length;
             i++)
        {
            string path =
                AssetDatabase.GUIDToAssetPath(
                    guids[i]);

            CharacterVerificationProfile profile =
                AssetDatabase.LoadAssetAtPath<
                    CharacterVerificationProfile>(
                        path);

            if (profile?.Bundle == bundle)
                return profile;
        }

        return null;
    }

    private static string BuildProfileId(
        CharacterAuthoringBundle bundle)
    {
        string bundlePath =
            AssetDatabase.GetAssetPath(
                bundle);

        string guid =
            AssetDatabase.AssetPathToGUID(
                bundlePath);

        return
            $"character.{bundle.Kind}." +
            (string.IsNullOrWhiteSpace(guid)
                ? bundle.name
                : guid);
    }

    private static void EnsureFolders()
    {
        EnsureFolder(
            "Assets",
            "2. Data");

        EnsureFolder(
            "Assets/2. Data",
            "CharacterVerification");

        EnsureFolder(
            RootFolder,
            "AutoGenerated");
    }

    private static void EnsureFolder(
        string parent,
        string child)
    {
        string path =
            parent + "/" + child;

        if (!AssetDatabase.IsValidFolder(path))
        {
            AssetDatabase.CreateFolder(
                parent,
                child);
        }
    }

    private static string Sanitize(
        string value)
    {
        string result =
            string.IsNullOrWhiteSpace(value)
                ? "Character"
                : value.Trim();

        foreach (char invalid
                 in Path.GetInvalidFileNameChars())
        {
            result =
                result.Replace(
                    invalid,
                    '_');
        }

        return result.Replace(
            ' ',
            '_');
    }
}
#endif
